### ISSUE TITLE
PravegaConnectorMiniYarnITCase failed if usePravegaVersionSubModule is set to false.

### ISSUE THREAD

**Issue by yangb8** [pravega/hadoop-connectors#38]
everything works well if I set usePravegaVersionSubModule to true (submodule build).  However, below exception will be thrown if it's set to false. So seems like there is some dependency issue. I tried to add all hadoop yarn jars, but still got this error.

io.pravega.connectors.hadoop.PravegaConnectorMiniYarnITCase > testPravegaConnector FAILED
    org.apache.hadoop.yarn.exceptions.YarnRuntimeException: org.apache.hadoop.yarn.webapp.WebAppException: Error starting http server
        at org.apache.hadoop.yarn.server.MiniYARNCluster.startResourceManager(MiniYARNCluster.java:347)
        at org.apache.hadoop.yarn.server.MiniYARNCluster.access$300(MiniYARNCluster.java:116)
        at org.apache.hadoop.yarn.server.MiniYARNCluster$ResourceManagerWrapper.serviceStart(MiniYARNCluster.java:468)
        at org.apache.hadoop.service.AbstractService.start(AbstractService.java:193)
        at org.apache.hadoop.service.CompositeService.serviceStart(CompositeService.java:120)
        at org.apache.hadoop.yarn.server.MiniYARNCluster.serviceStart(MiniYARNCluster.java:296)
        at org.apache.hadoop.service.AbstractService.start(AbstractService.java:193)
        at io.pravega.connectors.hadoop.PravegaConnectorMiniYarnITCase.setUp(PravegaConnectorMiniYarnITCase.java:73)

        Caused by:
        org.apache.hadoop.yarn.webapp.WebAppException: Error starting http server
            at org.apache.hadoop.yarn.webapp.WebApps$Builder.start(WebApps.java:310)
            at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager.startWepApp(ResourceManager.java:1078)
            at org.apache.hadoop.yarn.server.resourcemanager.ResourceManager.serviceStart(ResourceManager.java:1176)
            at org.apache.hadoop.service.AbstractService.start(AbstractService.java:193)
            at org.apache.hadoop.yarn.server.MiniYARNCluster.startResourceManager(MiniYARNCluster.java:339)
            ... 7 more

            Caused by:
            java.io.IOException: Unable to initialize WebAppContext
                at org.apache.hadoop.http.HttpServer2.start(HttpServer2.java:955)
                at org.apache.hadoop.yarn.webapp.WebApps$Builder.start(WebApps.java:306)
                ... 11 more

                Caused by:
                com.sun.jersey.api.container.ContainerException: No WebApplication provider is present
                    at com.sun.jersey.spi.container.WebApplicationFactory.createWebApplication(WebApplicationFactory.java:69)
                    at com.sun.jersey.spi.container.servlet.ServletContainer.create(ServletContainer.java:391)
                    at com.sun.jersey.spi.container.servlet.ServletContainer$InternalWebComponent.create(ServletContainer.java:306)
                    at com.sun.jersey.spi.container.servlet.WebComponent.load(WebComponent.java:607)
                    at com.sun.jersey.spi.container.servlet.WebComponent.init(WebComponent.java:210)
                    at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:373)
                    at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:710)
                    at com.google.inject.servlet.FilterDefinition.init(FilterDefinition.java:114)
                    at com.google.inject.servlet.ManagedFilterPipeline.initPipeline(ManagedFilterPipeline.java:98)
                    at com.google.inject.servlet.GuiceFilter.init(GuiceFilter.java:172)
                    at org.mortbay.jetty.servlet.FilterHolder.doStart(FilterHolder.java:97)
                    at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
                    at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:713)
                    at org.mortbay.jetty.servlet.Context.startContext(Context.java:140)
                    at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1282)
                    at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:518)
                    at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:499)
                    at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
                    at org.mortbay.jetty.handler.HandlerCollection.doStart(HandlerCollection.java:152)
                    at org.mortbay.jetty.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:156)
                    at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
                    at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
                    at org.mortbay.jetty.Server.doStart(Server.java:224)
                    at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
                    at org.apache.hadoop.http.HttpServer2.start(HttpServer2.java:933)
                    ... 12 more

**Comment by yangb8** [comment]
PR #41 is submitted for review

**Comment by yangb8** [comment]
PR #41 is merged
