### ISSUE TITLE
Resolve YarnMiniCluster guava dependency conflict with Pravega

### ISSUE THREAD

**Issue by vijikarthi** [pravega/hadoop-connectors#75]
**Problem description**
While addressing the fix for the issue https://github.com/pravega/hadoop-connectors/issues/64, I have found that the [PravegaConnectorMiniYarnITCase](https://github.com/pravega/hadoop-connectors/blob/master/src/test/java/io/pravega/connectors/hadoop/PravegaConnectorMiniYarnITCase.java#L74) failed to start and it is due to the `guava` jar dependency conflict. 

Pravega has the guava dependency `27.0.1-jre` whereas the yarn package library used in the connector project has guava dependency `com.google.guava:guava:11.0.2`. 

Relates to 
https://github.com/pravega/pravega/issues/1142
https://github.com/pravega/pravega/issues/1339

```
2019-03-22 15:29:07,548 INFO  [main] service.AbstractService (AbstractService.java:noteFailure(272)) - Service org.apache.hadoop.yarn.server.MiniYARNCluster$ResourceManagerWrapper_0 failed in state STARTED; cause: org.apache.hadoop.yarn.exceptions.YarnRuntimeException: java.lang.NoSuchFieldError: WHITESPACE
org.apache.hadoop.yarn.exceptions.YarnRuntimeException: java.lang.NoSuchFieldError: WHITESPACE
	at org.apache.hadoop.yarn.server.MiniYARNCluster.startResourceManager(MiniYARNCluster.java:349)
	at org.apache.hadoop.yarn.server.MiniYARNCluster.access$300(MiniYARNCluster.java:118)
	at org.apache.hadoop.yarn.server.MiniYARNCluster$ResourceManagerWrapper.serviceStart(MiniYARNCluster.java:479)
	at org.apache.hadoop.service.AbstractService.start(AbstractService.java:193)
	at org.apache.hadoop.service.CompositeService.serviceStart(CompositeService.java:120)
	at org.apache.hadoop.yarn.server.MiniYARNCluster.serviceStart(MiniYARNCluster.java:298)
	at org.apache.hadoop.service.AbstractService.start(AbstractService.java:193)
	at io.pravega.connectors.hadoop.PravegaConnectorMiniYarnITCase.setUp(PravegaConnectorMiniYarnITCase.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.contrib.java.lang.system.EnvironmentVariables$EnvironmentVariablesStatement.evaluate(EnvironmentVariables.java:122)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.NoSuchFieldError: WHITESPACE
	at org.apache.hadoop.yarn.webapp.WebApp.getPrefix(WebApp.java:265)
	at org.apache.hadoop.yarn.webapp.WebApp.parseRoute(WebApp.java:231)
	at org.apache.hadoop.yarn.webapp.WebApp.route(WebApp.java:219)
	at org.apache.hadoop.yarn.server.resourcemanager.webapp.RMWebApp.setup(RMWebApp.java:60)
```

**Problem location**
Hadoop Connector integration test [PravegaConnectorMiniYarnITCase](https://github.com/pravega/hadoop-connectors/blob/master/src/test/java/io/pravega/connectors/hadoop/PravegaConnectorMiniYarnITCase.java#L74)

**Suggestions for an improvement**

**Comment by crazyzhou** [comment]
Fixed via #76
